[package]
name = "ki18n-rs"
description = "A crate to use KF5I18n from rust."
author = ["Ayush Singh <ayushdevel1325@gmail.com>"]
version = "1.0.1"
edition = "2018"
links = "KF5I18n"
license = "MIT"
readme = "README.md"
repository = "https://github.com/Ayush1325/ki18n-rs"
keywords = ["ki18n", "kde", "localization"]
build = "build.rs"

[dependencies]
cpp = "0.5"
qmetaobject = "0.2"
qttypes = "0.2"

[build-dependencies]
cpp_build = "0.5"
semver = "1.0"

[package.metadata.docs.rs]
dependencies = ["qtbase5-dev", "qtdeclarative5-dev", "libqt5svg5-dev", "qtquickcontrols2-5-dev", "qml-module-org-kde-kirigami2", "kirigami2-dev", "libkf5i18n-dev", "gettext", "libkf5coreaddons-dev", "qml-module-qtquick-layouts"]
