[package]
name = "ki18n-rs"
description = "A crate to use KF5I18n from rust."
author = ["Ayush Singh <ayushdevel1325@gmail.com>"]
version = "1.0.0"
edition = "2018"
links = "KF5I18n"
license = "MIT"
license-file = "LICENSE.txt"
readme = "README.md"
repository = "https://github.com/Ayush1325/ki18n-rs"
keywords = ["ki18n", "kde", "localization"]

[dependencies]
cpp = "0.5"
qmetaobject = "0.2"
qttypes = "0.2"

[build-dependencies]
cpp_build = "0.5"
semver = "1.0"
