[package]
name = "ki18n-rs"
version = "0.1.0"
edition = "2018"
links = "KF5I18n"
license-file = "LICENSE.txt"
readme = "README.md"
repository = "https://github.com/Ayush1325/ki18n-rs"
keywords = ["ki18n", "kde", "localization"]

[dependencies]
cpp = "0.5"
qmetaobject = "0.2"
qttypes = "0.2"

[build-dependencies]
cpp_build = "0.5"
semver = "1.0"
pkg-config = "0.3"
